apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017